# Generated by Django 6.0.4 on 2026-04-25 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='子分類名稱')),
                ('category', models.CharField(choices=[('novum', '新異 (Novum)'), ('narrative', '敘事 (Narrative)'), ('theme', '主題 (Theme)')], max_length=20, verbose_name='所屬大類')),
                ('description', models.TextField(blank=True, verbose_name='群組概述')),
            ],
            options={
                'verbose_name': '概念子分類',
                'verbose_name_plural': '概念子分類',
                'ordering': ['category', 'name'],
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='概念名稱')),
                ('slug', models.SlugField(help_text='URL-friendly identifier. If duplicated across categories, prefix with category (e.g., novum-cyberpunk).', max_length=150, unique=True, verbose_name='URL 識別符')),
                ('category', models.CharField(choices=[('novum', '新異 (Novum)'), ('narrative', '敘事 (Narrative)'), ('theme', '主題 (Theme)')], max_length=20, verbose_name='分類')),
                ('description', models.TextField(blank=True, help_text='Detailed explanation. If external wiki exists, keep this brief.', verbose_name='概述')),
                ('related_concepts', models.ManyToManyField(blank=True, help_text='Concepts that are closely related for horizontal exploration.', to='concept.concept', verbose_name='相關概念')),
                ('group', models.ForeignKey(blank=True, help_text='Optional grouping for the Concept Hub UI.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concepts', to='concept.conceptgroup', verbose_name='子分類')),
            ],
            options={
                'verbose_name': '概念',
                'verbose_name_plural': '概念',
                'ordering': ['category', 'name'],
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='ConceptLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., SFE Entry, Wikipedia', max_length=200, verbose_name='連結標題')),
                ('url', models.URLField(max_length=500, verbose_name='網址')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='concept.concept', verbose_name='概念')),
            ],
            options={
                'verbose_name': '概念連結',
                'verbose_name_plural': '概念連結',
                'ordering': ['order'],
            },
        ),
    ]
