# Generated by Django 6.0.4 on 2026-05-01 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='概念名稱')),
                ('slug', models.SlugField(help_text='若有重複則為其添加分類前綴，例如 novum-cyberpunk。', max_length=150, unique=True, verbose_name='URL 識別符')),
                ('category', models.CharField(choices=[('novum', '新異 (Novum)'), ('narrative', '敘事 (Narrative)'), ('theme', '主題 (Theme)')], max_length=20, verbose_name='分類')),
                ('description', models.TextField(blank=True, help_text='若有外部連結則保持內容精簡。', verbose_name='概述')),
                ('related_concepts', models.ManyToManyField(blank=True, to='concept.concept', verbose_name='相關概念')),
            ],
            options={
                'verbose_name': '概念',
                'verbose_name_plural': '概念',
                'ordering': ['category', 'name'],
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='ConceptLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., SFE Entry, Wikipedia', max_length=200, verbose_name='連結標題')),
                ('url', models.URLField(max_length=500, verbose_name='網址')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='concept.concept', verbose_name='概念')),
            ],
            options={
                'verbose_name': '概念連結',
                'verbose_name_plural': '概念連結',
                'ordering': ['order'],
            },
        ),
    ]
