# Generated by Django 6.0.4 on 2026-05-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concept', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='related_concepts',
            field=models.ManyToManyField(blank=True, to='concept.concept', verbose_name='相關概念'),
        ),
    ]
