# Generated by Django 6.0.4 on 2026-04-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concept', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='description',
            field=models.TextField(blank=True, help_text='若有外部連結則保持內容精簡。', verbose_name='概述'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='slug',
            field=models.SlugField(help_text='若有重複則為其添加分類前綴，例如 novum-cyberpunk。', max_length=150, unique=True, verbose_name='URL 識別符'),
        ),
    ]
