# Generated by Django 6.0.4 on 2026-05-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concept', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['category'], name='concept_con_categor_d68039_idx'),
        ),
    ]
