# Generated by Django 6.0.4 on 2026-04-28 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concept', '0002_alter_concept_description_alter_concept_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concept',
            name='group',
        ),
        migrations.DeleteModel(
            name='ConceptGroup',
        ),
    ]
