# Generated by Django 6.0.4 on 2026-06-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concept', '0002_concept_concept_con_categor_d68039_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='featured_order',
            field=models.PositiveIntegerField(default=0, verbose_name='側欄排序'),
        ),
        migrations.AddField(
            model_name='concept',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='是否顯示作品檢索頁側欄。', verbose_name='精選標籤'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='category',
            field=models.CharField(choices=[('novum', '新異 (Novum)'), ('narrative', '敘事 (Narrative)'), ('theme', '主題 (Theme)')], default='theme', max_length=20, verbose_name='分類'),
        ),
    ]
