# Generated by Django 6.0.4 on 2026-06-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concept', '0003_concept_featured_order_concept_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='concept',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='concept',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='unique_concept_name_category'),
        ),
        migrations.AddConstraint(
            model_name='conceptlink',
            constraint=models.UniqueConstraint(fields=('concept', 'url'), name='unique_concept_url'),
        ),
    ]
