# Generated by Django 6.0.4 on 2026-06-13 06:57

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concept', '0004_alter_concept_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='description',
            field=models.TextField(blank=True, help_text='解釋這個概念的定義或背景。可留空。', verbose_name='描述'),
        ),
        migrations.CreateModel(
            name='HistoricalConcept',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('name', models.CharField(max_length=100, verbose_name='概念名稱')),
                ('slug', models.SlugField(help_text='若有重複則為其添加分類前綴，例如 novum-cyberpunk。', max_length=150, verbose_name='URL 識別符')),
                ('category', models.CharField(choices=[('novum', '新異 (Novum)'), ('narrative', '敘事 (Narrative)'), ('theme', '主題 (Theme)')], default='theme', max_length=20, verbose_name='分類')),
                ('is_featured', models.BooleanField(default=False, help_text='是否顯示作品檢索頁側欄。', verbose_name='精選標籤')),
                ('featured_order', models.PositiveIntegerField(default=0, verbose_name='側欄排序')),
                ('description', models.TextField(blank=True, help_text='解釋這個概念的定義或背景。可留空。', verbose_name='描述')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 概念',
                'verbose_name_plural': 'historical 概念',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
