# Generated by Django 6.0.4 on 2026-06-27 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concept', '0005_alter_concept_description_historicalconcept'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='此概念的其它稱呼，例如外文名或其它譯名。', max_length=255, verbose_name='別名')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='顯示順序')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='concept.concept', verbose_name='概念')),
            ],
            options={
                'verbose_name': '概念別名',
                'verbose_name_plural': '概念別名',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['name'], name='concept_con_name_fad44c_idx')],
                'constraints': [models.UniqueConstraint(fields=('concept', 'name'), name='unique_concept_alias')],
            },
        ),
    ]
