# Generated by Django 6.0.4 on 2026-07-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concept', '0006_conceptalias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='category',
            field=models.CharField(choices=[('novum', '新異 Novum'), ('narrative', '敘事 Narrative'), ('theme', '主題 Theme')], default='theme', max_length=20, verbose_name='分類'),
        ),
        migrations.AlterField(
            model_name='historicalconcept',
            name='category',
            field=models.CharField(choices=[('novum', '新異 Novum'), ('narrative', '敘事 Narrative'), ('theme', '主題 Theme')], default='theme', max_length=20, verbose_name='分類'),
        ),
    ]
