# Generated by Django 6.0.6 on 2026-08-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concept', '0007_alter_concept_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='note',
            field=models.TextField(blank=True, help_text='編目或行政用途，僅後台可見，不會顯示在網站上。可留空。', verbose_name='內部備註'),
        ),
        migrations.AddField(
            model_name='historicalconcept',
            name='note',
            field=models.TextField(blank=True, help_text='編目或行政用途，僅後台可見，不會顯示在網站上。可留空。', verbose_name='內部備註'),
        ),
    ]
