# Generated by Django 6.0.4 on 2026-05-01 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='名稱')),
                ('agent_type', models.CharField(choices=[('person', '個人'), ('organization', '組織')], default='person', max_length=20, verbose_name='類別')),
                ('about', models.TextField(blank=True, verbose_name='簡介')),
            ],
            options={
                'verbose_name': '主體',
                'verbose_name_plural': '主體',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['agent_type'], name='agent_agent_agent_t_3c7228_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='連結標籤')),
                ('url', models.URLField(max_length=500, verbose_name='網址')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='agent.agent', verbose_name='主體')),
            ],
            options={
                'verbose_name': '主體連結',
                'verbose_name_plural': '主體連結',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='AgentAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='別名')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='agent.agent', verbose_name='主體')),
            ],
            options={
                'verbose_name': '主體別名',
                'verbose_name_plural': '主體別名',
                'ordering': ['name'],
                'unique_together': {('agent', 'name')},
            },
        ),
    ]
