# Generated by Django 6.0.4 on 2026-05-14 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['name'], 'verbose_name': '人物/組織', 'verbose_name_plural': '人物/組織'},
        ),
        migrations.AlterModelOptions(
            name='agentalias',
            options={'ordering': ['name'], 'verbose_name': '人物/組織別名', 'verbose_name_plural': '人物/組織別名'},
        ),
        migrations.AlterModelOptions(
            name='agentlink',
            options={'ordering': ['label'], 'verbose_name': '人物/組織連結', 'verbose_name_plural': '人物/組織連結'},
        ),
        migrations.AlterField(
            model_name='agent',
            name='about',
            field=models.TextField(blank=True, help_text='關於此人物或組織的生平、經歷與背景介紹。可留空。', verbose_name='簡介'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_type',
            field=models.CharField(choices=[('person', '個人'), ('organization', '組織')], default='person', help_text='區分此為單一人物或是一個組織/團體。', max_length=20, verbose_name='類別'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(help_text='人物的真實姓名、最廣為人知的筆名，或組織的正式名稱。', max_length=255, verbose_name='名稱'),
        ),
        migrations.AlterField(
            model_name='agentalias',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='agent.agent', verbose_name='人物/組織'),
        ),
        migrations.AlterField(
            model_name='agentalias',
            name='name',
            field=models.CharField(help_text='此人物/組織使用的其他名稱，例如不同的筆名、本名、外文原名或各種譯名。', max_length=255, verbose_name='別名'),
        ),
        migrations.AlterField(
            model_name='agentlink',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='agent.agent', verbose_name='人物/組織'),
        ),
        migrations.AlterField(
            model_name='agentlink',
            name='label',
            field=models.CharField(help_text='顯示在網頁上的連結文字，例如「個人網站」、「維基百科」、「Twitter (X)」。', max_length=100, verbose_name='連結標籤'),
        ),
        migrations.AlterField(
            model_name='agentlink',
            name='url',
            field=models.URLField(help_text='完整的網址，請包含 https:// 開頭。', max_length=500, verbose_name='網址'),
        ),
    ]
