# Generated by Django 6.0.4 on 2026-05-01 14:13

from django.db import migrations


def migrate_publishers_to_agents(apps, schema_editor):
    Publisher = apps.get_model("work", "Publisher")
    Agent = apps.get_model("agent", "Agent")

    for publisher in Publisher.objects.all():
        agent, created = Agent.objects.get_or_create(
            name=publisher.name,
            defaults={
                "agent_type": "organization",
                "about": publisher.description,
            }
        )
    if created:
        Agent.objects.filter(pk=agent.pk).update(
            created_at=publisher.created_at,
            updated_at=publisher.updated_at
        )


def reverse_migrate(apps, schema_editor):
    pass

class Migration(migrations.Migration):
    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_publishers_to_agents, reverse_migrate),
    ]
