# Generated by Django 6.0.4 on 2026-05-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_alter_agent_options_alter_agentalias_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='agentalias',
            index=models.Index(fields=['name'], name='agent_agent_name_3e317d_idx'),
        ),
    ]
