# Generated by Django 6.0.4 on 2026-06-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_agentalias_agent_agent_name_3e317d_idx'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agentalias',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='agentalias',
            constraint=models.UniqueConstraint(fields=('agent', 'name'), name='unique_agent_alias'),
        ),
        migrations.AddConstraint(
            model_name='agentlink',
            constraint=models.UniqueConstraint(fields=('agent', 'url'), name='unique_agent_url'),
        ),
    ]
