# Generated by Django 6.0.6 on 2026-09-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_historicalagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='note',
            field=models.TextField(blank=True, help_text='編目或行政用途，僅後台可見，不會顯示在網站上。可留空。', verbose_name='內部備註'),
        ),
        migrations.AddField(
            model_name='historicalagent',
            name='note',
            field=models.TextField(blank=True, help_text='編目或行政用途，僅後台可見，不會顯示在網站上。可留空。', verbose_name='內部備註'),
        ),
    ]
