# Generated by Django 6.0.4 on 2026-05-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, help_text='前端顯示的作者名稱，以避免暴露登入帳號。', max_length=50, verbose_name='顯示名稱'),
        ),
    ]
