# Generated by Django 6.0.4 on 2026-06-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(help_text="程式內部的識別碼，例如 'contact_form_url'", max_length=100, unique=True, verbose_name='設定鍵值')),
                ('value', models.TextField(blank=True, help_text='網址或純文字內容', verbose_name='設定內容')),
                ('description', models.CharField(blank=True, help_text='管理員備註用的說明', max_length=200, verbose_name='備註說明')),
                ('is_active', models.BooleanField(default=True, help_text='停用後前端將無法取得此設定', verbose_name='是否啟用')),
            ],
            options={
                'verbose_name': '網站設定',
                'verbose_name_plural': '網站設定',
                'ordering': ['key'],
            },
        ),
    ]
