# Generated by Django 6.0.4 on 2026-04-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_type', models.CharField(choices=[('announcement', '公告'), ('article', '文章'), ('news', '消息')], max_length=20, verbose_name='類型')),
                ('title', models.CharField(max_length=300, verbose_name='標題')),
                ('body', models.TextField(help_text='支援 Markdown。', verbose_name='內文')),
                ('is_pinned', models.BooleanField(default=False, help_text='僅對公告有效，需手動取消。', verbose_name='置頂')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-created_at'],
            },
        ),
    ]
