# Generated by Django 6.0.4 on 2026-04-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='例如: about, faq, terms', unique=True, verbose_name='網址代稱')),
                ('title', models.CharField(max_length=300, verbose_name='標題')),
                ('body', models.TextField(help_text='支援 Markdown。', verbose_name='內文')),
            ],
            options={
                'verbose_name': '靜態頁面',
                'verbose_name_plural': '靜態頁面',
            },
        ),
    ]
