# Generated by Django 6.0.4 on 2026-05-01 18:23

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
        ('concept', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='程式內部使用的代號，例如：illustrator', max_length=50, unique=True, verbose_name='職責代號')),
                ('verb', models.CharField(help_text='例如：「某某某 繪」', max_length=10, verbose_name='動詞')),
                ('noun', models.CharField(help_text='例如：「繪師：某某某」', max_length=10, verbose_name='名詞')),
                ('description', models.CharField(blank=True, help_text='填表時的提示，例如：「小說封面的插畫」', max_length=100, verbose_name='說明')),
                ('order', models.PositiveIntegerField(default=0, help_text='控制下拉選單的顯示順序', verbose_name='排序')),
            ],
            options={
                'verbose_name': '職責',
                'verbose_name_plural': '職責',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300, verbose_name='系列名稱')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
            ],
            options={
                'verbose_name': '系列',
                'verbose_name_plural': '系列',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300, verbose_name='名稱')),
                ('catalogue_type', models.CharField(choices=[('award', '獎項'), ('reading_list', '書單'), ('anthology', '選集')], max_length=20, verbose_name='類型')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='年份')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('agent_curator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curated_catalogues', to='agent.agent', verbose_name='維護主體')),
            ],
            options={
                'verbose_name': '收錄目錄',
                'verbose_name_plural': '收錄目錄',
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300, verbose_name='名稱')),
                ('language', models.CharField(choices=[('zh-hant', '繁體中文'), ('zh-hans', '簡體中文'), ('en', '英文'), ('ja', '日文'), ('other', '其他')], default='zh-hant', max_length=20, verbose_name='出版品語言')),
                ('media', models.CharField(choices=[('book', '書籍'), ('magazine', '雜誌'), ('newspaper', '報紙'), ('website', '網站'), ('other', '其它')], max_length=20, verbose_name='出版品媒體')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='發行年份')),
                ('isbn', models.CharField(blank=True, max_length=50, verbose_name='ISBN')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='備註')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_publications', to='agent.agent', verbose_name='出版商')),
            ],
            options={
                'verbose_name': '出版品',
                'verbose_name_plural': '出版品',
                'ordering': ['year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Manifestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifestations', to='work.publication', verbose_name='出版品')),
            ],
            options={
                'verbose_name': '收錄作品紀錄',
                'verbose_name_plural': '收錄作品紀錄',
            },
        ),
        migrations.CreateModel(
            name='PublicationAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, help_text='若此處留空，將會使用人物的本名。用於翻譯名稱或特定筆名。', max_length=255, verbose_name='顯示名稱')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_contributions', to='agent.agent', verbose_name='主體')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='work.publication', verbose_name='出版品')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publication_agents', to='work.role', verbose_name='職責')),
            ],
            options={
                'verbose_name': '出版品主體關聯',
                'verbose_name_plural': '出版品主體關聯',
                'ordering': ['order'],
                'unique_together': {('publication', 'agent', 'role')},
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='agents',
            field=models.ManyToManyField(blank=True, related_name='publications', through='work.PublicationAgent', to='agent.agent', verbose_name='相關主體'),
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300, verbose_name='標題')),
                ('media_type', models.CharField(choices=[('novel', '小說'), ('comic', '漫畫')], max_length=20, verbose_name='媒體類型')),
                ('work_length', models.CharField(choices=[('long', '長篇'), ('short', '中短篇')], max_length=20, verbose_name='篇幅')),
                ('provenance', models.CharField(choices=[('original', '原創'), ('licensed', '代理')], max_length=20, verbose_name='作品來源')),
                ('language', models.CharField(choices=[('zh-hant', '繁體中文'), ('zh-hans', '簡體中文'), ('en', '英文'), ('ja', '日文'), ('other', '其他')], default='zh-hant', max_length=20, verbose_name='原始語言')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='發表年份')),
                ('description', models.TextField(blank=True, verbose_name='無劇透概述 (Synopsis)')),
                ('series_order', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='系列順序')),
                ('publications', models.ManyToManyField(related_name='works', through='work.Manifestation', to='work.publication', verbose_name='收錄於出版品')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='work.series', verbose_name='所屬系列')),
            ],
            options={
                'verbose_name': '作品',
                'verbose_name_plural': '作品',
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.AddField(
            model_name='manifestation',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifestations', to='work.work', verbose_name='作品'),
        ),
        migrations.CreateModel(
            name='WorkAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_contributions', to='agent.agent', verbose_name='主體')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_agents', to='work.role', verbose_name='職責')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='work.work', verbose_name='作品')),
            ],
            options={
                'verbose_name': '作品主體關聯',
                'verbose_name_plural': '作品主體關聯',
                'ordering': ['order'],
                'unique_together': {('work', 'agent', 'role')},
            },
        ),
        migrations.AddField(
            model_name='work',
            name='agents',
            field=models.ManyToManyField(blank=True, related_name='works', through='work.WorkAgent', to='agent.agent', verbose_name='相關主體'),
        ),
        migrations.CreateModel(
            name='WorkConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='說明該概念在此作品中如何運作。', verbose_name='概念應用詳述')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_concepts', to='concept.concept', verbose_name='概念')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_concepts', to='work.work', verbose_name='作品')),
            ],
            options={
                'verbose_name': '作品概念關聯',
                'verbose_name_plural': '作品概念關聯',
                'unique_together': {('work', 'concept')},
            },
        ),
        migrations.AddField(
            model_name='work',
            name='concepts',
            field=models.ManyToManyField(related_name='works', through='work.WorkConcept', to='concept.concept', verbose_name='相關概念'),
        ),
        migrations.AlterUniqueTogether(
            name='manifestation',
            unique_together={('work', 'publication')},
        ),
        migrations.CreateModel(
            name='CatalogueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='在書單中的排名或順序', verbose_name='排序')),
                ('note', models.CharField(blank=True, help_text='例如：獲獎、提名、首獎', max_length=200, verbose_name='收錄備註')),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='work.catalogue', verbose_name='所屬目錄')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_entries', to='work.work', verbose_name='作品')),
            ],
            options={
                'verbose_name': '目錄收錄紀錄',
                'verbose_name_plural': '目錄收錄紀錄',
                'ordering': ['order'],
                'unique_together': {('catalogue', 'work')},
            },
        ),
    ]
