# Generated by Django 6.0.4 on 2026-04-25 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('concept', '0002_alter_concept_description_alter_concept_slug'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='出版/發行商名稱')),
                ('description', models.TextField(blank=True, verbose_name='概述')),
            ],
            options={
                'verbose_name': '出版商',
                'verbose_name_plural': '出版商',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300, verbose_name='系列名稱')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
            ],
            options={
                'verbose_name': '系列',
                'verbose_name_plural': '系列',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300, verbose_name='名稱')),
                ('catalogue_type', models.CharField(choices=[('award', '獎項'), ('reading_list', '書單'), ('anthology', '選集')], max_length=20, verbose_name='類型')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='年份')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('curator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curated_catalogues', to='person.person', verbose_name='維護者')),
            ],
            options={
                'verbose_name': '收錄目錄',
                'verbose_name_plural': '收錄目錄',
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300, verbose_name='標題')),
                ('media_type', models.CharField(choices=[('novel', '小說'), ('comic', '漫畫')], max_length=20, verbose_name='媒體類型')),
                ('work_length', models.CharField(choices=[('long', '長篇'), ('short', '中短篇')], max_length=20, verbose_name='篇幅')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='發表年份')),
                ('description', models.TextField(blank=True, verbose_name='無劇透概述 (Synopsis)')),
                ('series_order', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='系列順序')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='work.series', verbose_name='所屬系列')),
            ],
            options={
                'verbose_name': '作品',
                'verbose_name_plural': '作品',
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300, verbose_name='名稱')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='發行年份')),
                ('isbn', models.CharField(blank=True, max_length=50, verbose_name='ISBN')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='備註')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='work.publisher', verbose_name='出版商')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='work.work', verbose_name='所屬作品')),
            ],
            options={
                'verbose_name': '出版品',
                'verbose_name_plural': '出版品',
                'ordering': ['year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='WorkConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='說明該概念在此作品中如何運作。', verbose_name='概念應用詳述')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_concepts', to='concept.concept', verbose_name='概念')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_concepts', to='work.work', verbose_name='作品')),
            ],
            options={
                'verbose_name': '作品概念關聯',
                'verbose_name_plural': '作品概念關聯',
                'unique_together': {('work', 'concept')},
            },
        ),
        migrations.AddField(
            model_name='work',
            name='concepts',
            field=models.ManyToManyField(related_name='works', through='work.WorkConcept', to='concept.concept', verbose_name='相關概念'),
        ),
        migrations.CreateModel(
            name='WorkCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('author', '作者'), ('co_author', '合著'), ('story', '原作'), ('art', '作畫')], max_length=20, verbose_name='角色')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_credits', to='person.person', verbose_name='人物')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='work.work', verbose_name='作品')),
            ],
            options={
                'verbose_name': '作品人物關聯',
                'verbose_name_plural': '作品人物關聯',
                'ordering': ['order'],
                'unique_together': {('work', 'person', 'role')},
            },
        ),
        migrations.AddField(
            model_name='work',
            name='persons',
            field=models.ManyToManyField(related_name='works', through='work.WorkCredit', to='person.person', verbose_name='相關人物'),
        ),
        migrations.CreateModel(
            name='PublicationCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('translator', '譯者'), ('editor', '編輯'), ('illustrator', '插畫')], max_length=20, verbose_name='角色')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_credits', to='person.person', verbose_name='人物')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='work.publication', verbose_name='出版品')),
            ],
            options={
                'verbose_name': '出版品人物關聯',
                'verbose_name_plural': '出版品人物關聯',
                'ordering': ['order'],
                'unique_together': {('publication', 'person', 'role')},
            },
        ),
        migrations.CreateModel(
            name='CatalogueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='在書單中的排名或順序', verbose_name='排序')),
                ('note', models.CharField(blank=True, help_text='例如：獲獎、提名、首獎', max_length=200, verbose_name='收錄備註')),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='work.catalogue', verbose_name='所屬目錄')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_entries', to='work.work', verbose_name='作品')),
            ],
            options={
                'verbose_name': '目錄收錄紀錄',
                'verbose_name_plural': '目錄收錄紀錄',
                'ordering': ['order'],
                'unique_together': {('catalogue', 'work')},
            },
        ),
    ]
