# Generated by Django 6.0.4 on 2026-05-02 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestation',
            name='name',
            field=models.CharField(blank=True, help_text='代表該作品在此出版物中的名稱，若與出版物名稱相同可留空。', max_length=300, verbose_name='篇名'),
        ),
        migrations.CreateModel(
            name='ManifestationAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, help_text='若此處留空，將會使用人物的本名。用於翻譯名稱或特定筆名。', max_length=255, verbose_name='顯示名稱')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifestation_contributions', to='agent.agent', verbose_name='主體')),
                ('manifestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='work.manifestation', verbose_name='具體呈現')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manifestation_agents', to='work.role', verbose_name='職責')),
            ],
            options={
                'verbose_name': '收錄作品參與者',
                'verbose_name_plural': '收錄作品參與者',
                'ordering': ['order'],
                'unique_together': {('manifestation', 'agent', 'role')},
            },
        ),
    ]
