# Generated by Django 6.0.4 on 2026-04-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='language',
            field=models.CharField(choices=[('zh-hant', '繁體中文'), ('zh-hans', '簡體中文'), ('en', '英文'), ('ja', '日文'), ('other', '其他')], default='zh-hant', max_length=20, verbose_name='出版品語言'),
        ),
        migrations.AddField(
            model_name='work',
            name='language',
            field=models.CharField(choices=[('zh-hant', '繁體中文'), ('zh-hans', '簡體中文'), ('en', '英文'), ('ja', '日文'), ('other', '其他')], default='zh-hant', max_length=20, verbose_name='原始語言'),
        ),
    ]
