# Generated by Django 6.0.4 on 2026-05-01 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_migrate_publisher_to_agent'),
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_publications', to='agent.agent', verbose_name='出版商'),
        ),
    ]
