# Generated by Django 6.0.4 on 2026-05-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_manifestation_name_manifestationagent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workconcept',
            name='description',
            field=models.CharField(blank=True, help_text='說明該概念在此作品中如何運作。', max_length=300, verbose_name='概念應用詳述'),
        ),
    ]
