# Generated by Django 6.0.4 on 2026-04-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_publication_language_work_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationcredit',
            name='display_name',
            field=models.CharField(blank=True, help_text='若此處留空，將會使用人物的本名。用於翻譯名稱或特定筆名。', max_length=255, verbose_name='顯示名稱'),
        ),
    ]
