# Generated by Django 6.0.4 on 2026-05-01 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_alter_publication_publisher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
