# Generated by Django 6.0.4 on 2026-05-03 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
        ('work', '0003_alter_workconcept_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogue',
            options={'ordering': ['title'], 'verbose_name': '精選', 'verbose_name_plural': '精選'},
        ),
        migrations.RemoveField(
            model_name='catalogue',
            name='agent_curator',
        ),
        migrations.RemoveField(
            model_name='catalogue',
            name='note',
        ),
        migrations.AddField(
            model_name='catalogue',
            name='about',
            field=models.TextField(blank=True, verbose_name='簡介'),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='agents',
            field=models.ManyToManyField(blank=True, related_name='curated_catalogues', to='agent.agent', verbose_name='維護者'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='catalogue_type',
            field=models.CharField(choices=[('award', '獎項'), ('reading_list', '書單')], max_length=20, verbose_name='類型'),
        ),
        migrations.AlterField(
            model_name='work',
            name='media_type',
            field=models.CharField(choices=[('novel', '小說'), ('comic', '漫畫')], max_length=20, verbose_name='體裁'),
        ),
        migrations.CreateModel(
            name='WorkCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(blank=True, help_text='例如：「最佳長篇小說」、「必讀」', max_length=100, verbose_name='項目')),
                ('status', models.CharField(choices=[('selected', '入選'), ('winner', '獲獎')], default='selected', max_length=20, verbose_name='入選狀態')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='備註')),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_catalogues', to='work.catalogue', verbose_name='精選')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_catalogues', to='work.work', verbose_name='作品')),
            ],
            options={
                'verbose_name': '目錄收錄紀錄',
                'verbose_name_plural': '目錄收錄紀錄',
                'unique_together': {('catalogue', 'work', 'category')},
            },
        ),
        migrations.DeleteModel(
            name='CatalogueEntry',
        ),
    ]
