# Generated by Django 6.0.4 on 2026-04-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_publicationcredit_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='provenance',
            field=models.CharField(choices=[('original', '原創'), ('licensed', '代理')], default='original', max_length=20, verbose_name='作品來源'),
            preserve_default=False,
        ),
    ]
