# Generated by Django 6.0.4 on 2026-05-01 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_delete_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='程式內部使用的代號，例如：illustrator', max_length=50, unique=True, verbose_name='職責代號')),
                ('verb', models.CharField(help_text='例如：「某某某 繪」', max_length=10, verbose_name='動詞')),
                ('noun', models.CharField(help_text='例如：「繪師：某某某」', max_length=10, verbose_name='名詞')),
                ('description', models.CharField(blank=True, help_text='填表時的提示，例如：「小說封面的插畫」', max_length=100, verbose_name='說明')),
                ('order', models.PositiveIntegerField(default=0, help_text='控制下拉選單的顯示順序', verbose_name='排序')),
            ],
            options={
                'verbose_name': '職責',
                'verbose_name_plural': '職責',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.AlterField(
            model_name='publicationcredit',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publication_credits', to='work.role', verbose_name='職責'),
        ),
        migrations.AlterField(
            model_name='workcredit',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_credits', to='work.role', verbose_name='職責'),
        ),
    ]
