# Generated by Django 6.0.4 on 2026-04-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_work_provenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='media',
            field=models.CharField(choices=[('book', '書籍'), ('magazine', '雜誌'), ('newspaper', '報紙'), ('website', '網站'), ('other', '其它')], default='book', max_length=20, verbose_name='出版品媒體'),
            preserve_default=False,
        ),
    ]
