# Generated by Django 6.0.4 on 2026-05-14 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_alter_catalogue_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Series',
            new_name='Cycle',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='series',
            new_name='cycle',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='series_order',
            new_name='cycle_order',
        ),
    ]
