# Generated by Django 6.0.4 on 2026-04-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
        ('work', '0005_publication_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='persons',
            field=models.ManyToManyField(related_name='publications', through='work.PublicationCredit', to='person.person', verbose_name='相關人物'),
        ),
    ]
