# Generated by Django 6.0.4 on 2026-05-14 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_rename_series_cycle_rename_series_work_cycle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300, verbose_name='叢書名稱')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
            ],
            options={
                'verbose_name': '叢書',
                'verbose_name_plural': '叢書',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='series_order',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='叢書順序'),
        ),
        migrations.AddField(
            model_name='publication',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, verbose_name='副標題'),
        ),
        migrations.AddField(
            model_name='publication',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='work.series', verbose_name='所屬叢書'),
        ),
    ]
