# Generated by Django 6.0.4 on 2026-05-14 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
        ('work', '0006_series_publication_series_order_publication_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cycle',
            options={'ordering': ['title'], 'verbose_name': '作品系列', 'verbose_name_plural': '作品系列'},
        ),
        migrations.AlterModelOptions(
            name='manifestation',
            options={'verbose_name': '收錄紀錄', 'verbose_name_plural': '收錄紀錄'},
        ),
        migrations.AlterModelOptions(
            name='manifestationagent',
            options={'ordering': ['order'], 'verbose_name': '收錄作品的參與者', 'verbose_name_plural': '收錄作品的參與者'},
        ),
        migrations.AlterModelOptions(
            name='publicationagent',
            options={'ordering': ['order'], 'verbose_name': '出版品參與者', 'verbose_name_plural': '出版品參與者'},
        ),
        migrations.AlterModelOptions(
            name='workagent',
            options={'ordering': ['order'], 'verbose_name': '作品創作者', 'verbose_name_plural': '作品創作者'},
        ),
        migrations.AlterModelOptions(
            name='workcatalogue',
            options={'verbose_name': '獎項與書單收錄紀錄', 'verbose_name_plural': '獎項與書單收錄紀錄'},
        ),
        migrations.AlterModelOptions(
            name='workconcept',
            options={'verbose_name': '作品相關概念', 'verbose_name_plural': '作品相關概念'},
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='about',
            field=models.TextField(blank=True, help_text='說明這個獎項或書單的背景、評選標準或來源。可留空。', verbose_name='簡介'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='agents',
            field=models.ManyToManyField(blank=True, help_text='負責評選或維護此獎項/書單的人物/組織。', related_name='curated_catalogues', to='agent.agent', verbose_name='維護者'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='catalogue_type',
            field=models.CharField(choices=[('award', '獎項'), ('reading_list', '書單')], help_text='「獎項」用於有評選與得獎結果的文學獎；「書單」用於推薦清單、必讀書目等。', max_length=20, verbose_name='類型'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='title',
            field=models.CharField(help_text='獎項或書單的正式名稱，例如「星雲獎」、「紐約時報書單」。', max_length=300, verbose_name='名稱'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='不同年度舉辦的賽事各自獨立，所以要填寫獎項與書單的年份。偶發、不分年度的可留空。', null=True, verbose_name='舉辦年份'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='note',
            field=models.TextField(blank=True, help_text='任何補充說明，例如系列別名或歷史沿革。可留空。', verbose_name='備註'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='title',
            field=models.CharField(help_text='作品所屬的系列名稱，例如「基地系列」、「瀚星系列」、「火星三部曲」。', max_length=300, verbose_name='作品系列名稱'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='name',
            field=models.CharField(blank=True, help_text='作品在這本出版品中使用了不同的篇名時填寫，例如同一篇短篇在不同選集中有不同譯名。作品與出版品名稱相同可留空。', max_length=300, verbose_name='在此出版品中的篇名'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifestations', to='work.publication', verbose_name='收錄於此出版品'),
        ),
        migrations.AlterField(
            model_name='manifestationagent',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifestation_contributions', to='agent.agent', verbose_name='人物/組織'),
        ),
        migrations.AlterField(
            model_name='manifestationagent',
            name='display_name',
            field=models.CharField(blank=True, help_text='若人物/組織在此篇使用了特定筆名或譯名時填寫，否則留空。', max_length=255, verbose_name='顯示名稱'),
        ),
        migrations.AlterField(
            model_name='manifestationagent',
            name='manifestation',
            field=models.ForeignKey(help_text='此人物/組織對應的收錄紀錄（作品 × 出版品）。', on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='work.manifestation', verbose_name='收錄紀錄'),
        ),
        migrations.AlterField(
            model_name='manifestationagent',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='同一職責有多人時，數字小的排前面。', verbose_name='顯示順序'),
        ),
        migrations.AlterField(
            model_name='manifestationagent',
            name='role',
            field=models.ForeignKey(help_text='通常是譯者，用以紀錄同一選集的作品有多名譯者的狀況。', on_delete=django.db.models.deletion.PROTECT, related_name='manifestation_agents', to='work.role', verbose_name='擔任的職責'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='agents',
            field=models.ManyToManyField(blank=True, related_name='publications', through='work.PublicationAgent', to='agent.agent', verbose_name='人物/組織'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='isbn',
            field=models.CharField(blank=True, help_text='書籍的 ISBN 編號，不含連字號。非書籍或不知道可留空。', max_length=50, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='language',
            field=models.CharField(choices=[('zh-hant', '繁體中文'), ('zh-hans', '簡體中文'), ('en', '英文'), ('ja', '日文'), ('other', '其他')], default='zh-hant', help_text='此出版品使用的語言，通常是讀者實際閱讀的語言。', max_length=20, verbose_name='出版語言'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='media',
            field=models.CharField(choices=[('book', '書籍'), ('magazine', '雜誌'), ('newspaper', '報紙'), ('website', '網站'), ('other', '其它')], max_length=20, verbose_name='出版形式'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='note',
            field=models.CharField(blank=True, help_text='補充說明，例如「此版本有刪節」等。可留空。', max_length=200, verbose_name='備註'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publisher',
            field=models.ForeignKey(blank=True, help_text='負責出版此作品的人物/組織，通常是商業出版社。不確定可留空。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_publications', to='agent.agent', verbose_name='出版商'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='series',
            field=models.ForeignKey(blank=True, help_text='出版品可隸屬於特定書系、叢書、類書等無序集合，或是期刊、報紙與雜誌等有序集合。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='work.series', verbose_name='所屬叢書/刊物'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='series_order',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='出版品在刊物內的順序，例如雜誌的總期數或是書籍的編號。', max_digits=5, null=True, verbose_name='叢書/刊物順序'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='subtitle',
            field=models.CharField(blank=True, help_text='例如《第五號屠宰場》的「兒童十字軍」；也能填寫雜誌名稱未包含的期號資訊。可留空。', max_length=300, verbose_name='副標題'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(help_text='書籍填書名，雜誌填期刊名稱，網站填網站名稱。', max_length=300, verbose_name='出版品名稱'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='此出版品正式發行的年份。不確定可留空。', null=True, verbose_name='發行年份'),
        ),
        migrations.AlterField(
            model_name='publicationagent',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_contributions', to='agent.agent', verbose_name='人物/組織'),
        ),
        migrations.AlterField(
            model_name='publicationagent',
            name='display_name',
            field=models.CharField(blank=True, help_text='若此人物/組織在這本出版品中使用了特定筆名或譯名，請填寫；否則留空，系統會自動使用登錄的本名。', max_length=255, verbose_name='顯示名稱'),
        ),
        migrations.AlterField(
            model_name='publicationagent',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='同一職責有多人時，數字小的排前面。', verbose_name='顯示順序'),
        ),
        migrations.AlterField(
            model_name='publicationagent',
            name='role',
            field=models.ForeignKey(help_text='人物/組織在此出版品中的職責，例如「編輯」和「繪師」。', on_delete=django.db.models.deletion.PROTECT, related_name='publication_agents', to='work.role', verbose_name='職責'),
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(help_text='僅供程式內部識別用，使用英文小寫與底線，例如：illustrator、cover_designer。不會對外顯示。', max_length=50, unique=True, verbose_name='職責代號'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.CharField(blank=True, help_text='在填表時顯示的補充說明，幫助填表者區分相近職責，例如「僅限小說封面插圖，漫畫作畫請用『畫』」。可留空。', max_length=100, verbose_name='說明'),
        ),
        migrations.AlterField(
            model_name='role',
            name='noun',
            field=models.CharField(help_text='接在職稱標題後使用，例如填「繪師」，顯示時會呈現為「繪師：王小明」。', max_length=10, verbose_name='名詞'),
        ),
        migrations.AlterField(
            model_name='role',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='數字越小越靠前，用來控制下拉選單中的排列順序。', verbose_name='顯示順序'),
        ),
        migrations.AlterField(
            model_name='role',
            name='verb',
            field=models.CharField(help_text='接在人名後面使用，例如填「繪」，顯示時會呈現為「王小明 繪」。', max_length=10, verbose_name='動詞形式'),
        ),
        migrations.AlterField(
            model_name='work',
            name='agents',
            field=models.ManyToManyField(blank=True, related_name='works', through='work.WorkAgent', to='agent.agent', verbose_name='人物/機構'),
        ),
        migrations.AlterField(
            model_name='work',
            name='cycle',
            field=models.ForeignKey(blank=True, help_text='若此作品屬於某個系列，請在此選取。獨立作品可留空。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='work.cycle', verbose_name='所屬系列'),
        ),
        migrations.AlterField(
            model_name='work',
            name='cycle_order',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='作品在系列中的正式編號或建議閱讀順序，例如第一冊填「1」。前傳或外傳可使用小數，例如「1.5」。可留空。', max_digits=5, null=True, verbose_name='系列中的順序'),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.TextField(blank=True, help_text='簡要介紹作品，例如 logline 或 synopsis。可留空', verbose_name='作品簡介'),
        ),
        migrations.AlterField(
            model_name='work',
            name='language',
            field=models.CharField(choices=[('zh-hant', '繁體中文'), ('zh-hans', '簡體中文'), ('en', '英文'), ('ja', '日文'), ('other', '其他')], default='zh-hant', help_text='作品最初發表時使用的語言。若作者採雙語發表，則各語系獨立登載。', max_length=20, verbose_name='原始語言'),
        ),
        migrations.AlterField(
            model_name='work',
            name='media_type',
            field=models.CharField(choices=[('novel', '小說'), ('comic', '漫畫')], help_text='作品的主要形式', max_length=20, verbose_name='體裁'),
        ),
        migrations.AlterField(
            model_name='work',
            name='provenance',
            field=models.CharField(choices=[('original', '原創'), ('licensed', '代理')], help_text='「原創」指本土或與本土關係密切的作者創作（如陳浩基）；「代理」指從海外取得版權於本土出版的作品（如劉慈欣）。此欄位為主觀判斷。', max_length=20, verbose_name='作品來源'),
        ),
        migrations.AlterField(
            model_name='work',
            name='publications',
            field=models.ManyToManyField(related_name='works', through='work.Manifestation', to='work.publication', verbose_name='收錄於哪些出版物'),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(help_text="作品最廣為人知的原文標題，例如 'Starship Troopers' 或「酔歩する男」。", max_length=300, verbose_name='標題'),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_length',
            field=models.CharField(choices=[('long', '長篇'), ('short', '中短篇')], help_text='長篇指單冊或多冊獨立成書的作品；中短篇則屬收錄於選集或期刊的作品。', max_length=20, verbose_name='篇幅'),
        ),
        migrations.AlterField(
            model_name='work',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='作品最早公開發表的年份，例如連載開始年或單行本初版年。不確定可留空。', null=True, verbose_name='首度發表年份'),
        ),
        migrations.AlterField(
            model_name='workagent',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_contributions', to='agent.agent', verbose_name='人物/機構'),
        ),
        migrations.AlterField(
            model_name='workagent',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='同一職責有多人時，數字小的排前面。不同職責之間的排序由職責類型本身控制。', verbose_name='顯示順序'),
        ),
        migrations.AlterField(
            model_name='workagent',
            name='role',
            field=models.ForeignKey(help_text='人物或機構在此作品中的職責，例如「作者」、「繪師」。', on_delete=django.db.models.deletion.PROTECT, related_name='work_agents', to='work.role', verbose_name='擔任的職責'),
        ),
        migrations.AlterField(
            model_name='workcatalogue',
            name='catalogue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_catalogues', to='work.catalogue', verbose_name='獎項/書單'),
        ),
        migrations.AlterField(
            model_name='workcatalogue',
            name='category',
            field=models.CharField(blank=True, help_text='獎項中的具體獎別，例如「最佳長篇小說」；書單中的分組，例如「必讀」、「推薦」。可留空。', max_length=100, verbose_name='項目'),
        ),
        migrations.AlterField(
            model_name='workcatalogue',
            name='note',
            field=models.CharField(blank=True, help_text='補充說明，例如「共同得獎」、「特別提及」等特殊情況。可留空。', max_length=255, verbose_name='備註'),
        ),
        migrations.AlterField(
            model_name='workcatalogue',
            name='status',
            field=models.CharField(choices=[('selected', '入選'), ('winner', '獲獎')], default='selected', help_text='「入選」表示進入候選名單但未得獎；「獲獎」表示最終得獎。書單類型請維持「入選」即可。', max_length=20, verbose_name='入選狀態'),
        ),
        migrations.AlterField(
            model_name='workconcept',
            name='description',
            field=models.CharField(blank=True, help_text='說明這個概念在作品中如何呈現，例如「時間旅行：以冬眠技術度過兩千年時光」。可留空。', max_length=300, verbose_name='在此作品中的應用方式'),
        ),
    ]
