# Generated by Django 6.0.4 on 2026-04-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_publication_persons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='work',
        ),
        migrations.AddField(
            model_name='publication',
            name='works',
            field=models.ManyToManyField(related_name='publications', to='work.work', verbose_name='收錄作品'),
        ),
        migrations.AlterField(
            model_name='publicationcredit',
            name='role',
            field=models.CharField(choices=[('author', '作者'), ('co_author', '合著'), ('story', '原作'), ('art', '作畫'), ('translator', '譯者'), ('editor', '編輯'), ('illustrator', '插畫')], max_length=20, verbose_name='角色'),
        ),
    ]
