# Generated by Django 6.0.4 on 2026-04-29 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_remove_publication_work_publication_works_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='works',
        ),
        migrations.CreateModel(
            name='WorkPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_publications', to='work.publication', verbose_name='出版品')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_publications', to='work.work', verbose_name='作品')),
            ],
            options={
                'verbose_name': '收錄作品紀錄',
                'verbose_name_plural': '收錄作品紀錄',
                'unique_together': {('work', 'publication')},
            },
        ),
        migrations.AddField(
            model_name='work',
            name='publications',
            field=models.ManyToManyField(related_name='works', through='work.WorkPublication', to='work.publication', verbose_name='收錄於出版品'),
        ),
    ]
