# Generated by Django 6.0.4 on 2026-05-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
        ('work', '0007_alter_cycle_options_alter_manifestation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='agents',
            field=models.ManyToManyField(blank=True, related_name='works', through='work.WorkAgent', to='agent.agent', verbose_name='人物/組織'),
        ),
    ]
