# Generated by Django 6.0.4 on 2026-05-14 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
        ('work', '0008_alter_work_agents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workagent',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_contributions', to='agent.agent', verbose_name='人物/組織'),
        ),
        migrations.AlterField(
            model_name='workagent',
            name='role',
            field=models.ForeignKey(help_text='人物或組織在此作品中的職責，例如「作者」、「繪師」。', on_delete=django.db.models.deletion.PROTECT, related_name='work_agents', to='work.role', verbose_name='擔任的職責'),
        ),
    ]
