# Generated by Django 6.0.4 on 2026-05-15 12:30

import apps.work.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_alter_workagent_agent_alter_workagent_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='不同年度舉辦的賽事各自獨立，所以要填寫獎項與書單的年份。偶發、不分年度的可留空。', null=True, validators=[apps.work.models.validate_not_future_year], verbose_name='舉辦年份'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='isbn',
            field=models.CharField(blank=True, help_text='書籍的 ISBN 編號，不含連字號。非書籍或不知道可留空。', max_length=50, validators=[apps.work.models.validate_isbn], verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='此出版品正式發行的年份。不確定可留空。', null=True, validators=[apps.work.models.validate_not_future_year], verbose_name='發行年份'),
        ),
        migrations.AlterField(
            model_name='work',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='作品最早公開發表的年份，例如連載開始年或單行本初版年。不確定可留空。', null=True, validators=[apps.work.models.validate_not_future_year], verbose_name='首度發表年份'),
        ),
    ]
