# Generated by Django 6.0.4 on 2026-05-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_alter_catalogue_year_alter_publication_isbn_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workconcept',
            options={'ordering': ['order'], 'verbose_name': '作品相關概念', 'verbose_name_plural': '作品相關概念'},
        ),
        migrations.AddField(
            model_name='workconcept',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='顯示順序'),
        ),
    ]
