# Generated by Django 6.0.4 on 2026-06-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0011_alter_workconcept_options_workconcept_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='catalogue',
            unique_together={('title', 'year')},
        ),
    ]
