# Generated by Django 6.0.4 on 2026-06-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0012_alter_catalogue_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='media_type',
            field=models.CharField(choices=[('novel', '小說'), ('poem', '詩'), ('comic', '漫畫')], help_text='作品的主要形式', max_length=20, verbose_name='體裁'),
        ),
    ]
