# Generated by Django 6.0.4 on 2026-06-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0013_alter_work_media_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='media_type',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='media',
            new_name='source',
        ),
        migrations.AddField(
            model_name='publication',
            name='media',
            field=models.CharField(
                choices=[('print', '紙本'), ('digital', '電子'), ('audio', '有聲')],
                default='print',
                max_length=20,
                verbose_name='出版媒材'
            ),
        ),
    ]
