# Generated by Django 6.0.4 on 2026-06-06 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0015_add_partial_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['pub_date', 'title'], 'verbose_name': '出版品', 'verbose_name_plural': '出版品'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['-ori_date', 'title'], 'verbose_name': '作品', 'verbose_name_plural': '作品'},
        ),
        migrations.RemoveField(
            model_name='publication',
            name='year',
        ),
        migrations.RemoveField(
            model_name='work',
            name='year',
        ),
        migrations.AlterField(
            model_name='publication',
            name='media',
            field=models.CharField(choices=[('print', '紙本'), ('digital', '電子'), ('audio', '有聲')], default='print', max_length=20, verbose_name='出版媒介'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pub_date',
            field=models.DateField(blank=True, help_text='此出版品正式發行的日期。只知道年份也可以填寫，會自動計算精確度。可留空', null=True, verbose_name='出版日期'),
        ),
        migrations.AlterField(
            model_name='work',
            name='ori_date',
            field=models.DateField(blank=True, help_text='作品最早公開發表的日期。只知道年份也可以填寫，會自動計算精確度。不確定可留空。', null=True, verbose_name='首度發表日期'),
        ),
        migrations.CreateModel(
            name='WorkRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('based_on', '衍生/改編 (主=衍生作, 受=原作)'), ('continues', '接續 (主=後作/續集, 受=前作)'), ('homage', '致敬 (主=致敬作, 受=被致敬的原作)'), ('related', '關聯 (無向，任填)')], help_text='定義這兩個作品間的語意。若為無向關係（如「關聯」），存檔時系統會自動標準化，無需在意主受詞順序。', max_length=20, verbose_name='關係')),
                ('note', models.TextField(blank=True, help_text='（選填）補充說明這段關係的細節，例如「僅借用世界觀」、「僅限電視版設定」等。', verbose_name='備註')),
                ('object_work', models.ForeignKey(help_text='被關聯的作品。通常為前作或原作，例如《科學怪人》之於〈潘渡娜〉。', on_delete=django.db.models.deletion.CASCADE, related_name='rels_as_object', to='work.work', verbose_name='受詞作品')),
                ('subject_work', models.ForeignKey(help_text='發起關聯的作品。通常為續作或衍生作，例如同人誌。', on_delete=django.db.models.deletion.CASCADE, related_name='rels_as_subject', to='work.work', verbose_name='主詞作品')),
            ],
            options={
                'verbose_name': '作品關聯',
                'verbose_name_plural': '作品關聯',
                'constraints': [models.UniqueConstraint(fields=('subject_work', 'object_work', 'kind'), name='unique_work_relation'), models.CheckConstraint(condition=models.Q(('subject_work', models.F('object_work')), _negated=True), name='no_self_reference_work_relation')],
            },
        ),
    ]
