# Generated by Django 6.0.4 on 2026-06-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0016_alter_publication_options_alter_work_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrelation',
            name='kind',
            field=models.CharField(choices=[('based_on', '衍生/改編 (主=衍生作, 受=原作)'), ('continues', '接續 (主=後作/續集, 受=前作)'), ('homage', '致敬 (主=致敬作, 受=被致敬的原作)'), ('related', '關聯 (無向，任填)')], help_text='定義這兩個作品間的關係。若為無向關係（如「關聯」），存檔時系統會自動標準化，無需在意主受詞順序。', max_length=20, verbose_name='關係'),
        ),
        migrations.AlterField(
            model_name='workrelation',
            name='note',
            field=models.CharField(blank=True, help_text='（選填）補充說明這段關係的細節，例如「致敬某某元素」、「參考某年某人訪談」等。', max_length=200, verbose_name='備註'),
        ),
    ]
