# Generated by Django 6.0.4 on 2026-06-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0017_alter_workrelation_kind_alter_workrelation_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrelation',
            name='kind',
            field=models.CharField(choices=[('based_on', '衍生 (主=衍生作, 受=原作)'), ('continues', '接續 (主=續作, 受=前作)'), ('homage', '致敬 (主=致敬作, 受=原作)'), ('related', '關聯 (無向，任填)')], help_text='定義這兩個作品間的關係。若為無向關係（如「關聯」），存檔時系統會自動標準化，無需在意主受詞順序。', max_length=20, verbose_name='關係'),
        ),
    ]
