# Generated by Django 6.0.4 on 2026-06-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_alter_agentalias_unique_together_and_more'),
        ('concept', '0004_alter_concept_unique_together_and_more'),
        ('work', '0018_alter_workrelation_kind'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='catalogue',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='manifestation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='manifestationagent',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='publicationagent',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='workagent',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='workcatalogue',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='workconcept',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='catalogue',
            constraint=models.UniqueConstraint(fields=('title', 'year'), name='unique_catalogue'),
        ),
        migrations.AddConstraint(
            model_name='manifestation',
            constraint=models.UniqueConstraint(fields=('work', 'publication'), name='unique_manifestation'),
        ),
        migrations.AddConstraint(
            model_name='manifestationagent',
            constraint=models.UniqueConstraint(fields=('manifestation', 'agent', 'role'), name='unique_manifestation_agent_role'),
        ),
        migrations.AddConstraint(
            model_name='publicationagent',
            constraint=models.UniqueConstraint(fields=('publication', 'agent', 'role'), name='unique_publication_agent_role'),
        ),
        migrations.AddConstraint(
            model_name='workagent',
            constraint=models.UniqueConstraint(fields=('work', 'agent', 'role'), name='unique_work_agent_role'),
        ),
        migrations.AddConstraint(
            model_name='workcatalogue',
            constraint=models.UniqueConstraint(fields=('catalogue', 'work', 'category'), name='unique_work_catalogue'),
        ),
        migrations.AddConstraint(
            model_name='workconcept',
            constraint=models.UniqueConstraint(fields=('work', 'concept'), name='unique_work_concept'),
        ),
    ]
