# Generated by Django 6.0.4 on 2026-06-13 06:57

import apps.work.models
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_historicalagent'),
        ('work', '0019_alter_catalogue_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCatalogue',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('title', models.CharField(help_text='獎項或書單的正式名稱，例如「星雲獎」、「紐約時報書單」。', max_length=300, verbose_name='名稱')),
                ('catalogue_type', models.CharField(choices=[('award', '獎項'), ('reading_list', '書單')], help_text='「獎項」用於有評選與得獎結果的文學獎；「書單」用於推薦清單、必讀書目等。', max_length=20, verbose_name='類型')),
                ('about', models.TextField(blank=True, help_text='說明這個獎項或書單的背景、評選標準或來源。可留空。', verbose_name='簡介')),
                ('year', models.PositiveSmallIntegerField(blank=True, help_text='不同年度舉辦的賽事各自獨立，所以要填寫獎項與書單的年份。偶發、不分年度的可留空。', null=True, validators=[apps.work.models.validate_not_future_year], verbose_name='舉辦年份')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 精選',
                'verbose_name_plural': 'historical 精選',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCycle',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('title', models.CharField(help_text='作品所屬的系列名稱，例如「基地系列」、「瀚星系列」、「火星三部曲」。', max_length=300, verbose_name='作品系列名稱')),
                ('note', models.TextField(blank=True, help_text='任何補充說明，例如系列別名或歷史沿革。可留空。', verbose_name='備註')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 作品系列',
                'verbose_name_plural': 'historical 作品系列',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPublication',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('title', models.CharField(help_text='書籍填書名，雜誌填期刊名稱，網站填網站名稱。', max_length=300, verbose_name='出版品名稱')),
                ('subtitle', models.CharField(blank=True, help_text='例如《第五號屠宰場》的「兒童十字軍」；也能填寫雜誌名稱未包含的期號資訊。可留空。', max_length=300, verbose_name='副標題')),
                ('series_order', models.DecimalField(blank=True, decimal_places=2, help_text='出版品在刊物內的順序，例如雜誌的總期數或是書籍的編號。', max_digits=5, null=True, verbose_name='叢書/刊物順序')),
                ('language', models.CharField(choices=[('zh-hant', '繁體中文'), ('zh-hans', '簡體中文'), ('en', '英文'), ('ja', '日文'), ('other', '其他')], default='zh-hant', help_text='此出版品使用的語言，通常是讀者實際閱讀的語言。', max_length=20, verbose_name='出版語言')),
                ('source', models.CharField(choices=[('book', '書籍'), ('magazine', '雜誌'), ('newspaper', '報紙'), ('website', '網站'), ('other', '其它')], max_length=20, verbose_name='出版形式')),
                ('media', models.CharField(choices=[('print', '紙本'), ('digital', '電子'), ('audio', '有聲')], default='print', max_length=20, verbose_name='出版媒介')),
                ('pub_date', models.DateField(blank=True, help_text='此出版品正式發行的日期。只知道年份也可以填寫，會自動計算精確度。可留空', null=True, verbose_name='出版日期')),
                ('pub_date_precision', models.CharField(choices=[('year', '年'), ('month', '月'), ('day', '日')], default='year', max_length=10, verbose_name='日期精確度')),
                ('isbn', models.CharField(blank=True, help_text='書籍的 ISBN 編號，不含連字號。非書籍或不知道可留空。', max_length=50, validators=[apps.work.models.validate_isbn], verbose_name='ISBN')),
                ('note', models.CharField(blank=True, help_text='補充說明，例如「此版本有刪節」等。可留空。', max_length=200, verbose_name='備註')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('publisher', models.ForeignKey(blank=True, db_constraint=False, help_text='負責出版此作品的人物/組織，通常是商業出版社。不確定可留空。', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agent.agent', verbose_name='出版商')),
                ('series', models.ForeignKey(blank=True, db_constraint=False, help_text='出版品可隸屬於特定書系、叢書、類書等無序集合，或是期刊、報紙與雜誌等有序集合。', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='work.series', verbose_name='所屬叢書/刊物')),
            ],
            options={
                'verbose_name': 'historical 出版品',
                'verbose_name_plural': 'historical 出版品',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSeries',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('title', models.CharField(max_length=300, verbose_name='叢書名稱')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 叢書',
                'verbose_name_plural': 'historical 叢書',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalWork',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('title', models.CharField(help_text="作品最廣為人知的原文標題，例如 'Starship Troopers' 或「酔歩する男」。", max_length=300, verbose_name='標題')),
                ('genre', models.CharField(choices=[('novel', '小說'), ('poem', '詩'), ('comic', '漫畫')], help_text='作品的主要形式', max_length=20, verbose_name='體裁')),
                ('work_length', models.CharField(choices=[('long', '長篇'), ('short', '中短篇')], help_text='長篇指單冊或多冊獨立成書的作品；中短篇則屬收錄於選集或期刊的作品。', max_length=20, verbose_name='篇幅')),
                ('provenance', models.CharField(choices=[('original', '原創'), ('licensed', '代理')], help_text='「原創」指本土或與本土關係密切的作者創作（如陳浩基）；「代理」指從海外取得版權於本土出版的作品（如劉慈欣）。此欄位為主觀判斷。', max_length=20, verbose_name='作品來源')),
                ('language', models.CharField(choices=[('zh-hant', '繁體中文'), ('zh-hans', '簡體中文'), ('en', '英文'), ('ja', '日文'), ('other', '其他')], default='zh-hant', help_text='作品最初發表時使用的語言。若作者採雙語發表，則各語系獨立登載。', max_length=20, verbose_name='原始語言')),
                ('ori_date', models.DateField(blank=True, help_text='作品最早公開發表的日期。只知道年份也可以填寫，會自動計算精確度。不確定可留空。', null=True, verbose_name='首度發表日期')),
                ('ori_date_precision', models.CharField(choices=[('year', '年'), ('month', '月'), ('day', '日')], default='year', max_length=10, verbose_name='日期精確度')),
                ('description', models.TextField(blank=True, help_text='簡要介紹作品，例如 logline 或 synopsis。可留空', verbose_name='作品簡介')),
                ('cycle_order', models.DecimalField(blank=True, decimal_places=2, help_text='作品在系列中的正式編號或建議閱讀順序，例如第一冊填「1」。前傳或外傳可使用小數，例如「1.5」。可留空。', max_digits=5, null=True, verbose_name='系列中的順序')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cycle', models.ForeignKey(blank=True, db_constraint=False, help_text='若此作品屬於某個系列，請在此選取。獨立作品可留空。', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='work.cycle', verbose_name='所屬系列')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 作品',
                'verbose_name_plural': 'historical 作品',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
