# Generated by Django 6.0.4 on 2026-06-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0020_historicalcatalogue_historicalcycle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpublication',
            name='binding',
            field=models.CharField(blank=True, choices=[('hardcover', '精裝'), ('paperback', '平裝'), ('softcover', '軟精裝'), ('saddle', '騎馬釘')], help_text='僅適用於紙本出版品，非紙本留空。', max_length=20, verbose_name='裝訂'),
        ),
        migrations.AddField(
            model_name='publication',
            name='binding',
            field=models.CharField(blank=True, choices=[('hardcover', '精裝'), ('paperback', '平裝'), ('softcover', '軟精裝'), ('saddle', '騎馬釘')], help_text='僅適用於紙本出版品，非紙本留空。', max_length=20, verbose_name='裝訂'),
        ),
    ]
