# Generated by Django 6.0.4 on 2026-06-27 04:08
# Hand-edited to preserve existing data while restructuring the catalogue models:
#   - Catalogue.year      -> WorkCatalogue.year   (award becomes a year-agnostic entity)
#   - WorkCatalogue.status -> WorkCatalogue.result (free text: 入選/獲獎/...)
#   - WorkCatalogue.category (text) -> Category FK scoped to the catalogue
# The category text->FK conversion is done via a temporary `category_new` field so the
# original text survives long enough to be migrated, then the old column is dropped.

import apps.work.models
import django.db.models.deletion
from django.db import migrations, models


def forward_catalogue_data(apps, schema_editor):
    WorkCatalogue = apps.get_model("work", "workcatalogue")
    Category = apps.get_model("work", "category")
    status_map = {"winner": "獲獎", "selected": "入選"}
    cat_cache = {}

    for wc in WorkCatalogue.objects.select_related("catalogue").all():
        # Pull the year off the (soon to be removed) parent catalogue.
        wc.year = wc.catalogue.year
        # The old status enum becomes a free-text result.
        wc.result = status_map.get(wc.status, "")
        # Normalise the old free-text category into a Category row scoped to the catalogue.
        text = (wc.category or "").strip()
        if text:
            key = (wc.catalogue_id, text)
            category = cat_cache.get(key)
            if category is None:
                category, _ = Category.objects.get_or_create(catalogue_id=wc.catalogue_id, name=text)
                cat_cache[key] = category
            wc.category_new = category
        wc.save(update_fields=["year", "result", "category_new"])


def reverse_catalogue_data(apps, schema_editor):
    # Irreversible in practice (Catalogue.year is dropped); nothing to restore.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0021_add_binding_to_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='獎項的組別或書單的分組，例如「短篇小說組」、「新詩組」、「必讀」。', max_length=100, verbose_name='組別名稱')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='數字越小越靠前，用來控制下拉選單中的排列順序。', verbose_name='顯示順序')),
            ],
            options={
                'verbose_name': '組別',
                'verbose_name_plural': '組別',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='catalogue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='work.catalogue', verbose_name='所屬獎項/書單'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('catalogue', 'name'), name='unique_catalogue_category'),
        ),
        migrations.AlterModelOptions(
            name='workcatalogue',
            options={'ordering': ['-year'], 'verbose_name': '獎項與書單收錄紀錄', 'verbose_name_plural': '獎項與書單收錄紀錄'},
        ),
        migrations.RemoveConstraint(
            model_name='catalogue',
            name='unique_catalogue',
        ),
        migrations.RemoveConstraint(
            model_name='workcatalogue',
            name='unique_work_catalogue',
        ),
        migrations.AddField(
            model_name='workcatalogue',
            name='result',
            field=models.CharField(blank=True, help_text='獎別或評價，自由填寫，例如「首獎」、「佳作」、「優選」、「入選」、「五星」、「必讀」。可留空。', max_length=50, verbose_name='結果'),
        ),
        migrations.AddField(
            model_name='workcatalogue',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='此筆收錄所屬的年份。可用來篩選歷年結果；不分年度的書單可留空。', null=True, validators=[apps.work.models.validate_not_future_year], verbose_name='屆次/年份'),
        ),
        # Temporary FK column so the original category text can be migrated before it is dropped.
        migrations.AddField(
            model_name='workcatalogue',
            name='category_new',
            field=models.ForeignKey(blank=True, help_text='此作品入選的組別，必須屬於同一個獎項/書單。無分組可留空。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_catalogues', to='work.category', verbose_name='組別'),
        ),
        migrations.RunPython(forward_catalogue_data, reverse_catalogue_data),
        migrations.RemoveField(
            model_name='workcatalogue',
            name='category',
        ),
        migrations.RenameField(
            model_name='workcatalogue',
            old_name='category_new',
            new_name='category',
        ),
        migrations.AddConstraint(
            model_name='workcatalogue',
            constraint=models.UniqueConstraint(fields=('catalogue', 'work', 'year', 'category'), name='unique_work_catalogue'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='about',
            field=models.TextField(blank=True, help_text='說明這個獎項或書單的背景、評選標準、來源，以及歷年沿革或制度變遷。可留空。', verbose_name='簡介'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='title',
            field=models.CharField(help_text='獎項或書單的正式名稱，例如「星雲獎」、「紐約時報書單」。不分年度，歷年共用同一筆。', max_length=300, unique=True, verbose_name='名稱'),
        ),
        migrations.AlterField(
            model_name='historicalcatalogue',
            name='about',
            field=models.TextField(blank=True, help_text='說明這個獎項或書單的背景、評選標準、來源，以及歷年沿革或制度變遷。可留空。', verbose_name='簡介'),
        ),
        migrations.AlterField(
            model_name='historicalcatalogue',
            name='title',
            field=models.CharField(db_index=True, help_text='獎項或書單的正式名稱，例如「星雲獎」、「紐約時報書單」。不分年度，歷年共用同一筆。', max_length=300, verbose_name='名稱'),
        ),
        migrations.RemoveField(
            model_name='historicalcatalogue',
            name='year',
        ),
        migrations.RemoveField(
            model_name='catalogue',
            name='agents',
        ),
        migrations.RemoveField(
            model_name='catalogue',
            name='year',
        ),
        migrations.RemoveField(
            model_name='workcatalogue',
            name='status',
        ),
    ]
