# Generated by Django 6.0.4 on 2026-07-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0023_historicalworkconcept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpublication',
            name='language',
            field=models.CharField(choices=[('zh-hant', '繁體中文'), ('zh-hans', '簡體中文'), ('nan', '台語'), ('hak', '客語'), ('en', '英文'), ('ja', '日文'), ('other', '其他')], default='zh-hant', help_text='此出版品使用的語言，通常是讀者實際閱讀的語言。混用多語時以主文語言為準，混用情形寫在備註。', max_length=20, verbose_name='出版語言'),
        ),
        migrations.AlterField(
            model_name='historicalwork',
            name='language',
            field=models.CharField(choices=[('zh-hant', '繁體中文'), ('zh-hans', '簡體中文'), ('nan', '台語'), ('hak', '客語'), ('en', '英文'), ('ja', '日文'), ('other', '其他')], default='zh-hant', help_text='作品最初發表時使用的語言。若作者採雙語發表，則各語系獨立登載。混用多語的作品以敘事主文的語言為準，混用情形可標記「混語書寫」概念標籤。', max_length=20, verbose_name='原始語言'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='language',
            field=models.CharField(choices=[('zh-hant', '繁體中文'), ('zh-hans', '簡體中文'), ('nan', '台語'), ('hak', '客語'), ('en', '英文'), ('ja', '日文'), ('other', '其他')], default='zh-hant', help_text='此出版品使用的語言，通常是讀者實際閱讀的語言。混用多語時以主文語言為準，混用情形寫在備註。', max_length=20, verbose_name='出版語言'),
        ),
        migrations.AlterField(
            model_name='work',
            name='language',
            field=models.CharField(choices=[('zh-hant', '繁體中文'), ('zh-hans', '簡體中文'), ('nan', '台語'), ('hak', '客語'), ('en', '英文'), ('ja', '日文'), ('other', '其他')], default='zh-hant', help_text='作品最初發表時使用的語言。若作者採雙語發表，則各語系獨立登載。混用多語的作品以敘事主文的語言為準，混用情形可標記「混語書寫」概念標籤。', max_length=20, verbose_name='原始語言'),
        ),
    ]
