# Generated by Django 6.0.6 on 2026-07-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0024_alter_historicalpublication_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwork',
            name='encoding_level',
            field=models.CharField(choices=[('secondary', '依二手資料著錄'), ('partial', '依著作本身部分著錄'), ('full', '依著作本身完整著錄')], default='secondary', help_text='此筆資料的著錄依據與完整度。「二手資料」指僅依網頁、書目索引等間接來源著錄；「部分」指已取得著作本身核對，但尚有欄位或關聯未填；「完整」指標題、創作者、概念、出版紀錄等適用欄位皆已依著作本身核對（不適用欄位可留空）。', max_length=20, verbose_name='著錄等級'),
        ),
        migrations.AddField(
            model_name='work',
            name='encoding_level',
            field=models.CharField(choices=[('secondary', '依二手資料著錄'), ('partial', '依著作本身部分著錄'), ('full', '依著作本身完整著錄')], default='secondary', help_text='此筆資料的著錄依據與完整度。「二手資料」指僅依網頁、書目索引等間接來源著錄；「部分」指已取得著作本身核對，但尚有欄位或關聯未填；「完整」指標題、創作者、概念、出版紀錄等適用欄位皆已依著作本身核對（不適用欄位可留空）。', max_length=20, verbose_name='著錄等級'),
        ),
    ]
