# Generated by Django 6.0.6 on 2026-08-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0025_historicalwork_encoding_level_work_encoding_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalwork',
            name='encoding_level',
            field=models.CharField(choices=[('minimal', '簡略著錄'), ('secondary', '間接著錄'), ('partial', '部分核校'), ('full', '完整核校')], default='minimal', help_text='此筆資料的著錄依據與完整度。簡略著錄：只登錄作品名或發表年份等識別資訊，尚未填寫作者、書介與出版紀錄。間接著錄：考據網路等二手資料，補充作者、書介、出版紀錄及可由書介判讀的概念標籤。部分核校：已取得並讀畢作品，核對間接著錄資訊，但仍有欄位或關聯未填。完整核校：已取得並讀畢作品，補充出版紀錄、親撰故事梗概、添加概念詳述、紀錄作品關聯。', max_length=20, verbose_name='著錄等級'),
        ),
        migrations.AlterField(
            model_name='work',
            name='encoding_level',
            field=models.CharField(choices=[('minimal', '簡略著錄'), ('secondary', '間接著錄'), ('partial', '部分核校'), ('full', '完整核校')], default='minimal', help_text='此筆資料的著錄依據與完整度。簡略著錄：只登錄作品名或發表年份等識別資訊，尚未填寫作者、書介與出版紀錄。間接著錄：考據網路等二手資料，補充作者、書介、出版紀錄及可由書介判讀的概念標籤。部分核校：已取得並讀畢作品，核對間接著錄資訊，但仍有欄位或關聯未填。完整核校：已取得並讀畢作品，補充出版紀錄、親撰故事梗概、添加概念詳述、紀錄作品關聯。', max_length=20, verbose_name='著錄等級'),
        ),
    ]
