# Generated by Django 6.0.6 on 2026-08-01 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_historicalagent'),
        ('work', '0026_alter_historicalwork_encoding_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalseries',
            name='publisher',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='發行此叢書的人物/組織，不確定可留空。', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agent.agent', verbose_name='出版商'),
        ),
        migrations.AddField(
            model_name='series',
            name='publisher',
            field=models.ForeignKey(blank=True, help_text='發行此叢書的人物/組織，不確定可留空。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_series', to='agent.agent', verbose_name='出版商'),
        ),
        migrations.CreateModel(
            name='SeriesPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='出版品在此叢書內的編號，例如「7」「E010」「第 245 期」，可留空。', max_length=50, verbose_name='叢書編號')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_publications', to='work.publication', verbose_name='出版品')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_publications', to='work.series', verbose_name='叢書/刊物')),
            ],
            options={
                'verbose_name': '叢書收錄',
                'verbose_name_plural': '叢書收錄',
                'ordering': ['series__title'],
                'constraints': [models.UniqueConstraint(fields=('series', 'publication'), name='unique_series_publication')],
            },
        ),
    ]
