# Generated by Django 6.0.6 on 2026-08-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0028_migrate_series_order_to_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpublication',
            name='series',
        ),
        migrations.RemoveField(
            model_name='historicalpublication',
            name='series_order',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='series_order',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='series',
        ),
        migrations.AddField(
            model_name='publication',
            name='series',
            field=models.ManyToManyField(blank=True, help_text='出版品可隸屬於特定書系、叢書、類書等無序集合，或是期刊、報紙與雜誌等有序集合。', related_name='publications', through='work.SeriesPublication', to='work.series', verbose_name='所屬叢書/刊物'),
        ),
    ]
