# Generated by Django 6.0.6 on 2026-08-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0029_convert_series_to_m2m'),
    ]

    operations = [
        # Pure rename: preserves existing note content under the new field, which
        # is now the *public* edition remark (e.g. "限量親簽版"). `note` is freed
        # up below to mean something new: an internal-only, admin-only note.
        migrations.RenameField(
            model_name='historicalpublication',
            old_name='note',
            new_name='edition_statement',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='note',
            new_name='edition_statement',
        ),
        migrations.AlterField(
            model_name='historicalpublication',
            name='edition_statement',
            field=models.CharField(blank=True, help_text='說明此版本的特殊之處，例如「限量親簽版」、「修訂新版新增後記」、「此版有刪節」等。可留空。', max_length=200, verbose_name='版本說明'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='edition_statement',
            field=models.CharField(blank=True, help_text='說明此版本的特殊之處，例如「限量親簽版」、「修訂新版新增後記」、「此版有刪節」等。可留空。', max_length=200, verbose_name='版本說明'),
        ),
        migrations.AddField(
            model_name='historicalpublication',
            name='note',
            field=models.TextField(blank=True, help_text='編目或行政用途，僅後台可見，不會顯示在網站上。可留空。', verbose_name='內部備註'),
        ),
        migrations.AddField(
            model_name='historicalwork',
            name='note',
            field=models.TextField(blank=True, help_text='編目或行政用途，僅後台可見，不會顯示在網站上。可留空。', verbose_name='內部備註'),
        ),
        migrations.AddField(
            model_name='publication',
            name='note',
            field=models.TextField(blank=True, help_text='編目或行政用途，僅後台可見，不會顯示在網站上。可留空。', verbose_name='內部備註'),
        ),
        migrations.AddField(
            model_name='work',
            name='note',
            field=models.TextField(blank=True, help_text='編目或行政用途，僅後台可見，不會顯示在網站上。可留空。', verbose_name='內部備註'),
        ),
    ]
