# Generated by Django 6.0.4 on 2026-04-25 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='姓名')),
                ('bio', models.TextField(blank=True, verbose_name='簡歷')),
            ],
            options={
                'verbose_name': '人物',
                'verbose_name_plural': '人物',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PersonLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Personal Website, Wikipedia', max_length=100, verbose_name='連結標題')),
                ('url', models.URLField(max_length=500, verbose_name='網址')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='person.person', verbose_name='人物')),
            ],
            options={
                'verbose_name': '人物連結',
                'verbose_name_plural': '人物連結',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PersonAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='別名')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='person.person', verbose_name='人物')),
            ],
            options={
                'verbose_name': '人物別名',
                'verbose_name_plural': '人物別名',
                'ordering': ['name'],
                'unique_together': {('person', 'name')},
            },
        ),
    ]
