# Generated by Django 6.0.4 on 2026-06-13 07:34

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='貢獻者名稱，匿名者可留空。', max_length=30, verbose_name='名稱')),
                ('is_anonymous', models.BooleanField(default=True, help_text='啟用時不公開顯示。', verbose_name='匿名')),
                ('about', models.TextField(blank=True, help_text='質性說明身分背景及主要貢獻，供表彰用。', verbose_name='簡述')),
            ],
            options={
                'verbose_name': '貢獻者',
                'verbose_name_plural': '貢獻者',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commit_type', models.CharField(choices=[('add', '新增'), ('fix', '勘誤'), ('update', '更新')], help_text='貢獻的性質。', max_length=10, verbose_name='類型')),
                ('scale', models.CharField(choices=[('field', '欄'), ('entry', '筆'), ('batch', '批')], help_text='貢獻的範圍大小。', max_length=10, verbose_name='規模')),
                ('title', models.CharField(help_text='一句話說明內容，例：新增《瑕疵人型》(2020)。', max_length=100, verbose_name='標題')),
                ('body', models.TextField(blank=True, help_text='詳細說明貢獻內容、取捨、原始資料等。', verbose_name='備註')),
                ('contributed_on', models.DateField(blank=True, help_text='實際發生日期，可留空。', null=True, verbose_name='貢獻日期')),
                ('contributor', models.ForeignKey(blank=True, help_text='留空表示來源不明或已合併自多人。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commits', to='commit.contributor', verbose_name='貢獻者')),
            ],
            options={
                'verbose_name': '貢獻紀錄',
                'verbose_name_plural': '貢獻紀錄',
                'ordering': ['-contributed_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCommit',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('commit_type', models.CharField(choices=[('add', '新增'), ('fix', '勘誤'), ('update', '更新')], help_text='貢獻的性質。', max_length=10, verbose_name='類型')),
                ('scale', models.CharField(choices=[('field', '欄'), ('entry', '筆'), ('batch', '批')], help_text='貢獻的範圍大小。', max_length=10, verbose_name='規模')),
                ('title', models.CharField(help_text='一句話說明內容，例：新增《瑕疵人型》(2020)。', max_length=100, verbose_name='標題')),
                ('body', models.TextField(blank=True, help_text='詳細說明貢獻內容、取捨、原始資料等。', verbose_name='備註')),
                ('contributed_on', models.DateField(blank=True, help_text='實際發生日期，可留空。', null=True, verbose_name='貢獻日期')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('contributor', models.ForeignKey(blank=True, db_constraint=False, help_text='留空表示來源不明或已合併自多人。', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='commit.contributor', verbose_name='貢獻者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 貢獻紀錄',
                'verbose_name_plural': 'historical 貢獻紀錄',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalContributor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('name', models.CharField(help_text='貢獻者名稱，匿名者可留空。', max_length=30, verbose_name='名稱')),
                ('is_anonymous', models.BooleanField(default=True, help_text='啟用時不公開顯示。', verbose_name='匿名')),
                ('about', models.TextField(blank=True, help_text='質性說明身分背景及主要貢獻，供表彰用。', verbose_name='簡述')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 貢獻者',
                'verbose_name_plural': 'historical 貢獻者',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
