# Generated by Django 6.0.4 on 2026-06-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='name',
            field=models.CharField(help_text='貢獻者名稱，不能留空。', max_length=30, unique=True, verbose_name='名稱'),
        ),
        migrations.AlterField(
            model_name='historicalcontributor',
            name='name',
            field=models.CharField(db_index=True, help_text='貢獻者名稱，不能留空。', max_length=30, verbose_name='名稱'),
        ),
    ]
